### ISSUE TITLE
Wiki issues

### ISSUE THREAD

**Issue by Tiagoquix** [Scags/TF2-Jailbreak-Redux#132]
Hello. I was reading the wiki's cvars page and I found two typos.

The explanation about the cvar `sm_tf2jr_lr_select_godmode` is duplicated, and the default value for `sm_tf2jr_freekill_silent` which is 30 exceeds its maximum value, which is 1.

I have two suggestions also: can you consider changing the default value of `sm_tf2jr_disguising` to `3`? The disguise effect is a cool idea on Jailbreak but many servers don't have it enabled. Here is a cool video demonstrating a Spy playing in a Jailbreak server with the disguise effect enabled: https://www.youtube.com/watch?v=hLwn96iaVfo

Also, can you consider changing the default value of `sm_tf2jr_warden_deny_lr` to `0`? Many Wardens simply deny the last request because they don't like it.

That's all.

**Comment by Scags** [comment]
The wiki page is what I jot down after an update, bound to screw that up eventually so I'll fix those in a second. The actual config file that is generated is always right, but the page is for sanity since those files are a bit unorganized.

As for changing default cvars, I don't think I want to do that. They can be changed obviously, so the default value shouldn't dictate how the server operates. If you're just a player you can always bring it up to the server owners themselves and ask if they can change it.
