### ISSUE TITLE
Perhaps revert mutes, Mute Guard Ban not functioning anymore

### ISSUE THREAD

**Issue by unusual917** [Scags/TF2-Jailbreak-Redux#15]
Hi Scags, by any chance on last update was mute system redone? Seems like there is a bug where muted players can join blu and get unmuted (perhaps it happens at roundstart). Not sure if you use it but it is confirmed bug on my end.

edit** I noticed he did have similar names with another player in the server, are they getting muted by unique id's or by name? Perhaps this may be why? Not sure.

**Comment by Scags** [comment]
Odd, that shouldn't happen. However since you compiled the plugin yourself, you might've missed out on some dependencies. Check your sourcemod/scripting/include/ folder and make sure that you have sourcecomms.inc in there. That is, if you're using SourceBans or SourceBans++. If you aren't then that's quite odd how that happened.

**Comment by unusual917** [comment]
Hi Scags, any chance you can provide the include in the repo? I can't seem to find one that works without errors (compilation errors like invalid function or declaration).

What version of sourcemod are you using also for the compile?

**Comment by Scags** [comment]
I'm using the latest 1.9 compiler with the latest snapshot of includes. In the next update, the 1.9 version includes will be required because of the `RemoveEntity()` native that I'll be using more often.
[Here](https://github.com/ppalex7/SourceComms/blob/master/game_upload/scripting/include/sourcecomms.inc) is the include you're looking for.

**Comment by unusual917** [comment]
Thank you sir. Will use that instead.

**Comment by unusual917** [comment]
Scags, I used the latest compiler/snapshots and the sourcecomm include, but it gives me these errors
![image](https://user-images.githubusercontent.com/24946482/43979230-ee25a71a-9c9e-11e8-833a-f9cef3042696.png)

Any idea what may be causing it?

**Comment by Scags** [comment]
Not sure on this one, I'll look into it later. In the meantime, there's a debugging command to check gamemode properties.
Try `sm_getprop bSC`
If you are responded with a `1` then there is actually an issue that needs fixing most likely.
Otherwise, if you get a `0`, then sourcecomms (or sourcebans++¹) isn't running.

1: It depends on what you're running on your server. If you are running sourcebans, you're probably running sourcecomms. If you **aren't** running sourcecomms, then you are using basecomms. (I think this is included in sourcemod by default.) If you are running sourcebans++, then you have sourcecomms (renamed sbpp_comms but still works) running.

In less-wordy terms:

- sourcebans and not sourcecomms ==> **basecomms**
- sourcebans and sourcecomms ==> **sourcecomms**
- sourcebans++ ==> **sourcecomms**
- neither ==> **basecomms**

**Comment by Scags** [comment]
Closing, works on my side. Don't forget that this only fires when the round is active.
