### ISSUE TITLE
How do I implement this idea

### ISSUE THREAD

**Issue by q1085909155** [Scags/TF2-Jailbreak-Redux#162]
I need a function to help me write my plug-in.
For example: the last request for the next round is Warday
What SHOULD I write to make the PLUGIN I write recognize that the next round is Warday, so that I can make changes to some of the functionality of my PLUGIN

Because some plug-ins will conflict with the last request.
For example, I have a plugin that modifies the character model of the Blue team at the beginning of a turn, if the last request for the next turn is HHH Kill Round, then the character model for all blue teams after the turn starts will not be Horhorheadless Horseman

Also, I have been running Jail Server in my country for 2-3 years and I hope someone can maintain this plugin :)

Because it's really good

It would be better if someone could provide me with some JIL-compatible plug-ins, because I am the only Server running Jail Server in my country, I hope someone can give me some help

**Comment by MrPanica** [comment]
I did not fully understand your idea, since English is not my native language (I am Russian), but here is a small code that checks at the beginning of the round (when the players first appear on the map) what LR was chosen in the previous round, and if in configuration of this LR is the setting `"IsWarday" "1"`, then your code will be executed.

This is the easiest way to implement it, in my opinion.
If your code from another plugin is executed just at the beginning of the round, then just substitute this check.

```

#include <tf2jailredux>

public void OnPluginStart()
{
	HookEvent("teamplay_round_start", OnPreRoundStart);
}

public Action OnPreRoundStart(Event event, const char[] name, bool dontBroadcast)
{
	int LR = JBGameMode_GetProp("iLRPresetType");

	if(LR != -1)
	{
		LastRequest Nextlr = LastRequest.At(LR);
		if(Nextlr.GetParameterNum("IsWarday") == 1)
		{
			PrintToChatAll("Curr Round Is Warday");
		}
	}
}
```

**Comment by q1085909155** [comment]
Большое спасибо за помощь, мне просто нужно
`
int LR = JBGameMode_GetProp("iLRPresetType");
if(LR != -1)
`
Хорошо.
Но твои расширенные знания помогли мне сделать больше. Большое спасибо.
