### ISSUE TITLE
A few good suggestions

### ISSUE THREAD

**Issue by MrPanica** [Scags/TF2-Jailbreak-Redux#33]
-Prophunt-
Make it possible to turn into a map texture.
If the hunter caused damage to the prisoner, then the hunter is not deprived of HP.

-Gameplay-
Add a rebel system and set up role effects.

--------------------------------------------------------
Sorry for my English

**Comment by Scags** [comment]
I wish I could do that with Prophunt, a lot of the props are custom, and I'm not a mapper, so me finding out how to figure that stuff out would kinda suck. Plus if I went through the precache table, I'd find some *interesting* models that probably would help either.
Hunter health loss happens when you shoot, so what I could do would give a "leech" effect. The damage dealt to the props would come back as health.

Yes, I probably need to do that. I might as well add the role renderers .cfg for everything else while I'm at it.
Thanks for the feedback.
