### ISSUE TITLE
DR option

### ISSUE THREAD

**Issue by YoinksX2** [Scags/TF2-Jailbreak-Redux#45]
The option to reduce the round time when a player is given lr is great. However if a player wants death request it instantly ruins the round if the warden accidentally gives it to the red. So perhaps give make a Deathrequest option that sets the time to whatever the server host wants? Maybe make it like custom lr in the sense that you can type in chat what you want blues to do and have it display at the bottom of the screen.

**Comment by Scags** [comment]
I'm trying to decipher what you're saying. If you mean to make a separate command for wardens strictly for death requests, I don't think that that's something I'd like to have in the plugin. More or less because of the effort required to create a new functionality within the gamemode. If you mean to make a separate last request in the menu for death requests, that would *also* suck because of the failsafes and exceptions needed for that single last request. The other issue with that would be because the timer is set once the last request menu pops up, not after a last request is chosen. I appreciate the thought but that isn't something I'd prefer to look forward to doing at the moment.
Also there isn't a maximum value for the cvar so you could always just make it obnoxiously large or something.
