### ISSUE TITLE
Rebel system timer

### ISSUE THREAD

**Issue by Salamon75** [Scags/TF2-Jailbreak-Redux#50]
I enabled the rebel system and noticed that everyone who rebel get removed after one second.
Then I noticed in config that minimum set too 0. max set to 1.00 so even though the timer set 30 it is still 1 mp.

// Timer for the Rebel system, if it's enabled.
// -
// Default: "30"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_tf2jr_rebel_timer "30"

**Comment by MrPanica** [comment]
I already wrote to the author about this error. It is in the process of fixing and is likely to be fixed with the next update.
https://github.com/Scags/TF2-Jailbreak-Redux/issues/44

But if you don’t want to wait, fix one thing in TF2Jail_Redux.sp

Replace it
`CreateConVar ("sm_tf2jr_rebel_timer", "30", "Timer for the Rebel system, if it's enabled.", FCVAR_NOTIFY, true, 0.0, true, 1.0);`

on this
`CreateConVar ("sm_tf2jr_rebel_timer", "30", "Timer for the Rebel system, if it's enabled.", FCVAR_NOTIFY, true, 0.0, true, 30);`
30 is the maximum time (in seconds)

Also correct the time in the config

**Comment by Scags** [comment]
Patched in latest update.
